apiVersion: v1
kind: Pod
metadata:
  name: hallo-welt
  namespace: websites
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: http
          containerPort: 80
